field: 87fa42ae-cdb3-48ca-a5b4-80df97ced5bc # Icon Grid
fieldLayouts:
  8c1d6609-7312-4700-b103-422871ed1068:
    tabs:
      -
        elements:
          -
            fieldUid: b6cd1ab1-15c9-44a7-a272-96583dc2757b # Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b78439b9-48fd-4d9a-9783-fa8f11caacfe
            warning: null
            width: 50
          -
            fieldUid: f68e9a51-f020-4eaf-8378-33e8197236a8 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a98e441-65f4-43a7-9e96-19dfa31260df
            warning: null
            width: 50
        name: Content
        uid: 00387fc5-415d-443b-a3ea-235eabb61670
fields:
  b6cd1ab1-15c9-44a7-a272-96583dc2757b: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:09773b73-a304-4513-84fd-c4d5d4dd953a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:09773b73-a304-4513-84fd-c4d5d4dd953a' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Select Icon'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f68e9a51-f020-4eaf-8378-33e8197236a8: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: icon
name: Icon
sortOrder: 1
