field: 845c4d3c-77ca-498c-abfc-c923b56c257a
fieldLayouts:
  350dfec5-22b2-4ca7-a168-228d51449c8c:
    tabs:
      -
        fields:
          808de827-54e1-4656-9faa-498dc49a6d78:
            required: true
            sortOrder: 1
          973e24a8-d7d9-4072-83fc-5e86d98ba38c:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  808de827-54e1-4656-9faa-498dc49a6d78:
    contentColumnType: text
    fieldGroup: null
    handle: topLevelItem
    instructions: "You may select an entry, provide a URL or link to an asset for the top level item.\r\n\r\nPlease note: if you choose to provide a URL, you MUST also provide \"Custom link text\", otherwise the link will appear blank. Entry links with no custom link text will fall back on the title of the entry. Asset links with no custom link text will use the name of the file."
    name: 'Top Level Item'
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames:
        1: asset
        3: entry
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  973e24a8-d7d9-4072-83fc-5e86d98ba38c:
    contentColumnType: string
    fieldGroup: null
    handle: columnLinks
    instructions: ''
    name: 'Column Links'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - a5122e92-6ea2-485f-90de-d19fa34b7964
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_columnlinks}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: 'Add a Column Link'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: navItem
name: 'Nav Item'
sortOrder: 1
