field: 0ab4908b-bab6-4e71-ae0b-a5b6098cdaa2
fieldLayouts:
  23c58abe-25af-4ebd-83e7-a7274537ec15:
    tabs:
      -
        fields:
          572d5ceb-17dc-41f7-a83f-09f6629ead11:
            required: true
            sortOrder: 1
          e64822fb-fcca-4268-bbd0-904594ef1765:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  572d5ceb-17dc-41f7-a83f-09f6629ead11:
    contentColumnType: text
    fieldGroup: null
    handle: topLevelItem
    instructions: "You may select an entry or provide a URL for the top level item.\r\n\r\nPlease note: if you choose to provide a URL, you MUST also provide \"Custom link text\", otherwise the link will appear blank. Entry links with no custom link text will fall back on the title of the entry."
    name: 'Top Level Item'
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames:
        3: entry
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  e64822fb-fcca-4268-bbd0-904594ef1765:
    contentColumnType: string
    fieldGroup: null
    handle: dropdownLinks
    instructions: ''
    name: 'Dropdown Links'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 3b513ac1-6451-43f1-a7f0-c2339d8cb885
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_10_dropdownlinks}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: 'Add a Dropdown Link'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: navItem
name: 'Nav Item'
sortOrder: 1
