fieldLayouts:
  4c30df90-4a47-47ff-b88d-2e54fcf588eb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: 'For admin reference only - not shown.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b37e73ea-b232-4b6c-876e-86cf23bb2c76
            warning: null
            width: 100
          -
            fieldUid: 6978af6e-566d-496d-abfc-884513d509b9 # Alert
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f906c9bf-4c89-4563-8fd5-26b7455d6efc
            warning: null
            width: 100
        name: Content
        uid: 5c982499-f939-4890-8623-22e2d55ccb3d
handle: alert
hasTitleField: true
name: Alert
section: b7a6ad8e-d32a-4f3b-9ac7-c8a0d7d9e616 # Alerts
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
