fieldLayouts:
  4c30df90-4a47-47ff-b88d-2e54fcf588eb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41c354d0-3d14-4408-889f-c613013c9d46
            warning: null
            width: 100
          -
            fieldUid: 6978af6e-566d-496d-abfc-884513d509b9 # Alert
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7befb4b7-37f9-4e25-b2b3-946cbc918c25
            warning: null
            width: 100
        name: Content
        uid: 155b0727-7c90-4456-bce9-26d865bc9c4d
handle: alert
hasTitleField: true
name: Alert
section: b7a6ad8e-d32a-4f3b-9ac7-c8a0d7d9e616 # Alerts
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
