color: null
fieldLayouts:
  25e832d4-be1c-41d4-836b-00f72ac16c5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T18:09:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1d60a696-8784-48df-bff4-bb8b52b5f56d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T18:10:35+00:00'
            elementCondition: null
            fieldUid: ff11a7ef-4804-4699-9e26-f9d531a7e760 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f78a48e6-0909-4cd0-bd7a-17f0bb8e1c28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T18:10:35+00:00'
            elementCondition: null
            fieldUid: b03ef84f-ced1-471e-80e2-b9679dedfd88 # Resource Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cf2bea8-6cdd-455f-91b6-1598948ef670
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: be2b67a6-33b2-46a1-846f-e1ffc52adbba
        userCondition: null
handle: callToAction
hasTitleField: false
icon: ''
name: 'Call To Action'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
