color: null
fieldLayouts:
  123eea2e-7bd9-4581-a8a5-3854d9f5f314:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T20:23:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dfbf632e-9b71-40c8-ab31-01f869c1caff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:28:03+00:00'
            elementCondition: null
            fieldUid: dd58c3c0-4afc-4b83-a606-73c8bc282d99 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Card Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 339ea7bc-89dd-455a-adfb-7c59465452f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:28:03+00:00'
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: 'Card Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26923d59-6866-49a2-b24f-def3487936ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:28:03+00:00'
            elementCondition: null
            fieldUid: ff11a7ef-4804-4699-9e26-f9d531a7e760 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: 'Card Content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d543d4a3-ed4a-4e33-9036-bd66aa29d018
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:28:03+00:00'
            elementCondition: null
            fieldUid: b03ef84f-ced1-471e-80e2-b9679dedfd88 # CTA Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7492727-8360-4411-af07-06e91351e26a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 172492ab-8bdc-4ac1-af46-9af06c239a16
        userCondition: null
handle: card
hasTitleField: false
icon: ''
name: Card
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
