fieldLayouts:
  4c1545a0-c310-4ae2-a1d1-541eac1ea70b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1aee5b94-b8f3-40b4-8f9b-6d2fd789c6d0
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8f7794d-b155-4bbd-b503-04d27ed14309
            warning: null
            width: 100
        name: Content
        uid: c024a2ba-6304-4437-bc26-fa62ef65f5fb
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccc52fdf-5cf4-4210-97c5-9b10c2aed5e3
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 527efe88-19f4-4c5d-972d-8468da682095
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1f6fdca-326d-4d55-ab17-bddd7ad336fa
            warning: null
            width: 100
        name: SEO
        uid: b3faee81-9158-456e-a2c9-ae6644bf8f71
handle: contactPage
hasTitleField: true
name: 'Contact Page'
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
