color: null
fieldLayouts:
  5b9055a0-0c41-4e8e-920b-696471f89b3d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T17:08:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e24e6d06-e485-426f-afa2-a015fb8b925c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-08-15T17:10:34+00:00'
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4f0aab9-b1bd-4b58-9804-8f8e838dc230
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-16T14:22:31+00:00'
            elementCondition: null
            fieldUid: 8678d5b0-ebe6-4da8-9111-e5ccf5c13386 # General Toggle Off
            handle: null
            includeInCards: false
            instructions: null
            label: 'Open Link In New Window'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 749a8663-8773-47df-8cdd-a50c128a6173
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 3baa2ba0-099c-4dd9-bd77-ac3ef47246c1
        userCondition: null
handle: ctaLink
hasTitleField: true
icon: ''
name: 'CTA Link'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
