color: null
fieldLayouts:
  ea84b4b7-06a8-4f02-9933-f73ae4a40608:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T16:33:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 68903edd-a7a4-408d-b513-d8bb24749f31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 341a7fb3-3ede-4a66-8e32-25c38b986f8a # Event Start Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6083a0fb-b0d3-4550-a855-e1c0ee66fb3f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 6695f59b-2131-411b-9ed2-35f957256c1a # Event End Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e824743-c02d-4b2c-b22a-8d37b42baa41
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: f155fe39-4c36-418a-829b-8e9bfcd3fa1d # Event Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3880b582-6778-46de-b9e5-3c501cee7c5c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 1734b2b5-03f5-435f-a92a-5b5e6125f9bc # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 487d91f8-d92c-42b6-a8f7-5c26b643b20f
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 06a0af26-9155-4550-96d8-d319faabf257
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 0587c309-76fe-4928-9be3-cb2980b7908c # Content Designer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8eaf4301-724f-40e7-b096-7613b289ca3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da24b561-9e70-4886-a47c-98dd4dd23072
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 1d7fd420-3fd4-4dc0-afca-1833e0d9a05c # SEOMatic Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f47aa22-6a8e-478e-b1fd-f5fa751a37cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 678939a0-3ca0-4044-b263-e25151ebb1df # Additional Header Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55463759-56db-4cd5-ae6f-52b3c4cbfeeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T16:38:42+00:00'
            elementCondition: null
            fieldUid: 3e4455cb-a3c6-4a1f-aece-f5b32088a23e # Additional Footer Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2d8843c-eb60-437e-85c2-ad7a0bd47dfb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: c8a5850b-437e-416e-b047-6912e81d20d0
        userCondition: null
handle: event
hasTitleField: true
icon: ''
name: Event
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
