fieldLayouts:
  e20267cc-14f4-404a-8584-47f2d9632f91:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e3623c0e-c855-4e75-b639-9690b7d9e060
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49142c87-79ae-4b48-b7e7-edccc587eff4
            warning: null
            width: 100
        name: Hero
        uid: efe393fb-af8d-48b9-a708-66019715dbb0
      -
        elements:
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22b953a2-54e4-4c5c-b29a-b714cf53b36e
            warning: null
            width: 100
        name: Content
        uid: 8be7cd25-ed27-44eb-bdf0-119c4e95101f
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4865f86-7e5b-4943-9e88-08cc5401a390
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7190620-9468-40e9-80e6-db14caf4b6df
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6bc27cc-fb4d-4dde-ac8e-f851416f413a
            warning: null
            width: 100
        name: SEO
        uid: d45d1d84-0761-4a2c-a311-813fc956e0bc
handle: homepage
hasTitleField: true
name: Homepage
section: 804ebac0-45d8-49c0-9e1f-418cc9c708e7 # Homepage
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
