color: null
fieldLayouts:
  6e6b0216-5d3f-4f54-9de4-cac73ac59725:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-19T15:07:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 653666e5-8466-4a6c-9dbf-6c6fc81e8510
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T15:13:09+00:00'
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 131fb942-4184-4c34-bb2d-722a8619f59a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T15:09:24+00:00'
            elementCondition: null
            fieldUid: dd58c3c0-4afc-4b83-a606-73c8bc282d99 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94a187a-a522-4c4c-b477-7c9d0ef1ebf9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T15:09:24+00:00'
            elementCondition: null
            fieldUid: ff11a7ef-4804-4699-9e26-f9d531a7e760 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a57189cc-9676-417a-862c-b71b73d7eddf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T15:09:24+00:00'
            elementCondition: null
            fieldUid: b03ef84f-ced1-471e-80e2-b9679dedfd88 # Resource Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee5497c9-f758-4d3e-b158-fcdd91486fe8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a22b222b-3e6a-4f05-85cd-0916741299b0
        userCondition: null
handle: imageCard
hasTitleField: false
icon: ''
name: 'Image Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
