color: red
fieldLayouts:
  4383c1fb-e88c-4b39-ad25-fff4334ad240:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-16T14:16:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e1f3bc2-4270-4b43-8b34-d1bedb9360c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T14:22:38+00:00'
            elementCondition: null
            fieldUid: b03ef84f-ced1-471e-80e2-b9679dedfd88 # CTA Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'Navigation Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17c94820-e3e2-44f1-8bba-05b9e0de04cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T15:24:10+00:00'
            elementCondition: null
            fieldUid: c6cce9ed-155f-4196-95bf-f8dde0bff9b1 # Navigation Groups
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4258edd-f406-4ce7-8d3f-cd092f96dc10
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T14:22:38+00:00'
            elementCondition: null
            fieldUid: 2b4abe74-65a4-4e1f-a224-ab97e43e54d9 # Column Span
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2125fe2f-dcd5-408a-b398-7bb02a4955f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1d06a92-df49-47a6-b3dc-fcc4dceccbd9
        userCondition: null
handle: navigationLink
hasTitleField: false
icon: ''
name: 'Navigation Link'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
