color: null
fieldLayouts:
  e9c13e8c-26bc-4d3d-ba67-85e721133652:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-16T14:24:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f62d6adf-97da-43d7-b89e-6ce184a30efc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T14:26:51+00:00'
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8511cce-68dd-463a-a2ea-5b7601fa7ea3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T15:26:37+00:00'
            elementCondition: null
            fieldUid: 6eef63ba-f2a8-4833-8b72-8a6a9d931f84 # Navigation Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f218eaf7-ee80-4ea7-b4d9-8e4f06349771
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T14:26:51+00:00'
            elementCondition: null
            fieldUid: 2b4abe74-65a4-4e1f-a224-ab97e43e54d9 # Column Span
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 493b7bc1-243f-4fd1-afcd-787da440a5fe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27c31dbc-bb3a-42ff-916b-1267aa417e26
        userCondition: null
handle: navigationGroup
hasTitleField: false
icon: ''
name: 'Navigation Group'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
