fieldLayouts:
  0fb58f60-6744-484d-917e-3fbe9e0234ba:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 06d572aa-ef4e-4bbd-9c80-383044f40885
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dacdf19-0fa1-4f4a-87d2-1e1ab0d764c2
            warning: null
            width: 100
        name: Hero
        uid: 16bf5f61-d586-4670-ba9f-3af6e347184b
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 931a328a-dae5-467d-8222-7e661a7d824c
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cbae48c-75c6-4774-9a48-2d079c480244
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65007c60-12a3-4b0e-a968-61ef2c7ed19c
            warning: null
            width: 100
        name: SEO
        uid: bb16e377-0733-4e92-a9a8-2eea1cff26cf
handle: newsPage
hasTitleField: true
name: 'News Page'
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
