fieldLayouts:
  0fb58f60-6744-484d-917e-3fbe9e0234ba:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 90e0a020-4c0c-4795-817c-64ed39380c35
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b7005f0-575a-4d1f-92d7-2d64dc232466
            warning: null
            width: 100
        name: Hero
        uid: 5adb8797-9284-49cd-ab03-135635fc07f1
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 952457b1-1727-4ade-97af-06f5ba28ba80
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53db7261-080c-4475-b1b4-c83e9786f903
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62af9c2d-50a6-42cc-a7a3-b1679ca9eb27
            warning: null
            width: 100
        name: SEO
        uid: b28fdb30-859e-4d7f-95b6-1b39a0a0718d
handle: newsPage
hasTitleField: true
name: 'News Page'
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
