fieldLayouts:
  4e5979ac-1357-4a9f-82a0-518c1c980b52:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 083d8bc2-dc80-48e2-aa56-a74dde026668
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e20d1262-1ab9-474d-bbd4-8cc9d11de2b7
            warning: null
            width: 100
        name: Hero
        uid: 9eeacd6c-1d39-4692-9ba5-80eb0e93f481
      -
        elements:
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9194d806-68e6-49b7-be3e-b590b99687db
            warning: null
            width: 100
        name: Content
        uid: 55c68c5b-f498-4642-8900-e94fa1cafe15
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec42e63a-23a1-4ea2-9d11-9fa346eac594
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 018c5ede-681d-4f9c-9e8c-359dab30eedb
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef297408-cb8b-46ce-82f1-4ab8e8b7a8c8
            warning: null
            width: 100
        name: SEO
        uid: 08896a4e-53aa-4d01-880e-f29ceb76184b
handle: notFoundPage
hasTitleField: true
name: '404 Page'
section: aa4b309e-df7a-47cf-9aa5-25285f46796f # 404 Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
