fieldLayouts:
  2ddbcba1-3b17-491c-9a1f-2a5122491715:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b2676fc3-f18b-49aa-a25e-2640bd935793
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e81ad2c1-8534-4dba-bcc0-5a846bea93c5
            warning: null
            width: 100
        name: Hero
        uid: e9ba6c08-5511-4e72-b476-a4e667cb97b8
      -
        elements:
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0724940a-7f60-4f39-ac0d-cbc4b82cf492
            warning: null
            width: 100
        name: Content
        uid: ed5f6624-0c88-404c-a5f9-9b2fdf634c2a
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ef1e21d-9c93-45bb-9d35-7adb7b571f58
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56750362-d451-4072-935c-489e9b5426d8
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2677f413-f41c-441e-9778-e67f7c068240
            warning: null
            width: 100
        name: SEO
        uid: fc0599a7-5d6a-4b97-8184-ff686b0d431f
handle: page
hasTitleField: true
name: Page
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
