fieldLayouts:
  2ddbcba1-3b17-491c-9a1f-2a5122491715:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff5bd715-2098-4a33-94da-2142fc15036a
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72e258cd-0848-48bc-b5bc-c73628d7bc55
            warning: null
            width: 100
        name: Hero
        uid: 6ea64fb9-9fa4-41f1-9203-db8dd65fe99d
      -
        elements:
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76762f21-c23c-43c2-9bea-15cdc1fda10c
            warning: null
            width: 100
        name: Content
        uid: 4e209829-a6c1-4dbb-945c-bc43ee258abb
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c45b7475-b515-426e-8bc1-9c7b36199c5e
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58b38c69-e665-40ad-aa00-e336df1b13f2
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd447ad8-5d47-4b13-9c57-f5b572f03078
            warning: null
            width: 100
        name: SEO
        uid: ad499fa8-7127-4a2d-88da-2571a8b73ff5
handle: page
hasTitleField: true
name: Page
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
