color: null
fieldLayouts:
  396963b4-704a-43c3-ba9b-61c30a8de2ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-07T17:20:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c78810a6-b5d3-4fc2-8fc4-f0b1724e767f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T17:23:24+00:00'
            elementCondition: null
            fieldUid: bd4fb97b-3b89-49bc-9fdb-c20917cb6776 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1faff01-f847-4b8f-b4a5-e069c74bc78d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T17:23:24+00:00'
            elementCondition: null
            fieldUid: 1734b2b5-03f5-435f-a92a-5b5e6125f9bc # Abstract
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6212fe3-5ca4-4dc5-b14c-a43b1a7e5caf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T17:23:24+00:00'
            elementCondition: null
            fieldUid: 880ea67a-2b41-468b-b4af-0e2799aee9b3 # Public/Sorting Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac362b64-3c7b-4615-9fc7-863b713b1835
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T17:23:24+00:00'
            elementCondition: null
            fieldUid: 69705774-001e-4d43-b76b-77eef5713301 # Resource Types
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89b519a6-f4d9-46a4-ae9a-f35c25314d26
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T17:23:24+00:00'
            elementCondition: null
            fieldUid: 4d061e2c-2f20-41b2-9e12-d11cb1fded64 # Resource Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1507377-06cf-4e07-90c5-b53e7d938776
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T17:27:41+00:00'
            elementCondition: null
            fieldUid: b03ef84f-ced1-471e-80e2-b9679dedfd88 # Resource Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d06b947-2216-484e-a1a9-d961b298127d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 290c7125-7cc5-48dc-822d-84efacfd94bb
        userCondition: null
handle: resourceLink
hasTitleField: true
icon: ''
name: 'Direct Link'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
