fieldLayouts:
  d20835c1-2f59-4ee5-b54d-788dc9d4205d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 0f8aa3f7-de9e-4beb-a7e9-e98793b3b60e # Featured Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e6810524-42e4-4e35-8fe8-edfb548dd138 # Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d5e98a9a-c478-4cf5-8c85-1083950e2e9f # Resource Date
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86444c22-bd97-4a40-9136-f5613c95ba48 # Resource Types
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c97b95b-c74a-41d8-be93-7607a191617d # Resource Topics
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93e2b1ce-6b60-40c8-ad40-4b1c92d2ecd1 # Resource
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Resource
        sortOrder: 1
handle: resourceLink
hasTitleField: true
name: 'Direct Link'
section: 31726602-42e3-461e-ad79-08d69e6e899a # Resources
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
