fieldLayouts:
  f562c5d2-1619-40b1-9d82-65d4347b087c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 63d7e2eb-85e4-42f4-93d8-7c38213b520e
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dfd421a-5118-4add-8d88-8273fb7e8ecb
            warning: null
            width: 100
        name: Hero
        uid: 6e4a2113-9dd5-4e8a-9ce5-83f2f296ee85
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d959e17d-1abc-470a-bdf4-1892a2ea01a4
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 700c2227-2b1a-485a-b77b-e013a0bbe8c4
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93a7880c-6643-44bf-a4fe-e5e9ea47f57e
            warning: null
            width: 100
        name: SEO
        uid: 94b5b851-8623-4057-9ce9-05df938f6475
handle: resourcesPage
hasTitleField: true
name: 'Resources Page'
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
