fieldLayouts:
  645a65f2-ba3e-489e-a506-53888b688a58:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 40e8da97-83f8-4790-b2d6-577bf2052e1f
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fcbc14f-706f-4a7a-8f3a-025473863191
            warning: null
            width: 100
        name: Hero
        uid: 0c34aced-8129-4792-ae44-5bc3482265f9
      -
        elements:
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85fea7dd-0125-4c68-9665-d8dfac6c4ae1
            warning: null
            width: 100
        name: Content
        uid: a47d923c-7f42-4ba4-ad31-ee5174929976
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1002dacb-d7f3-41fa-bd24-eceab6e3b97e
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a9da2da-519a-41eb-95d7-e812a1927ad9
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16e201a9-f364-431f-b796-28e4d6688d7e
            warning: null
            width: 100
        name: SEO
        uid: ed012513-111e-49cb-b478-2cb36d8b52ab
handle: serviceUnavailablePage
hasTitleField: true
name: 'Service Unavailable Page'
section: d44a5a95-fa08-4efd-8496-2ac825c5acd1 # Service Unavailable Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
