color: sky
fieldLayouts:
  841f2f33-5104-4bd0-be00-17061f90eb1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T20:31:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54001396-1d6b-40ae-93e3-d346ca67b3ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:33:56+00:00'
            elementCondition: null
            fieldUid: 3b057048-977f-4c40-ba97-63d84a65f907 # Shared Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99e90eb1-c242-4f2b-9841-60d7030aa800
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f68e3551-5eba-4824-a3d4-9d67fb6dfd4e
        userCondition: null
handle: sharedSection
hasTitleField: false
icon: ''
name: 'Shared Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
