fieldLayouts:
  26a6743b-375d-4250-b3e1-7e399520fb34:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5ae5da38-7c36-408c-8aa9-9fdbf7c571f8
            warning: null
            width: 100
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abe31f0c-ce66-4d6d-b3cc-2305a0611c83
            warning: null
            width: 100
        name: 'Shared Block'
        uid: 33e805bc-b85e-4df5-8b9d-f23067e43df7
handle: sharedSection
hasTitleField: true
name: 'Shared Section'
section: 16e6b8c8-fd2d-4fa3-9219-9d81e2ab1e98 # Shared Sections
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
