fieldLayouts:
  26a6743b-375d-4250-b3e1-7e399520fb34:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f964639e-0884-41a7-ab79-090e7f23c571
            warning: null
            width: 100
          -
            fieldUid: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c44a3f4-6890-4de1-b78f-c46d043cc273
            warning: null
            width: 100
        name: 'Shared Block'
        uid: 74cc1977-9b72-45b7-80b7-8ac896a7bddb
handle: sharedSection
hasTitleField: true
name: 'Shared Section'
section: 16e6b8c8-fd2d-4fa3-9219-9d81e2ab1e98 # Shared Sections
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
