fieldLayouts:
  f2f3cdc7-bc0a-4644-b309-4199a7738742:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f69d75e5-81aa-4c89-ab92-7b143f213283
            warning: null
            width: 100
          -
            fieldUid: 8c2e7523-1da7-4283-8f22-be2cfd5d251b # Select Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b97cbc7e-11e0-4ab0-9ec7-b48d161e0b31
            warning: null
            width: 100
        name: Content
        uid: d7692290-0148-4ebf-be8c-290652fe32f9
      -
        elements:
          -
            fieldUid: 9e20857f-1af8-4551-a171-4756ce866036 # SEOMatic Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f74d419-4b8a-49dc-87b6-9443d2d2aa3f
            warning: null
            width: 100
          -
            fieldUid: d1edff97-994f-4f78-9318-6cdbbdfd446d # Additional Header Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 649eaabb-a8ea-4527-ad5c-344e1f9c1225
            warning: null
            width: 100
          -
            fieldUid: e60a84f5-789c-489b-a95e-ae0419f4ae7d # Additional Footer Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3656eeb2-bc0b-4418-95d9-bd69a73e8426
            warning: null
            width: 100
        name: SEO
        uid: 4a3d8677-238b-477f-bbba-d57fa86114d8
handle: teamPage
hasTitleField: true
name: 'Team Page'
section: 9b2e55cd-41cc-43c8-a0e9-17aa24519787 # Pages
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
