headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
toolbar:
  - heading
  - '|'
  - numberedList
  - bulletedList
  - bold
  - italic
  - link
  - insertImage
  - mediaEmbed
  - undo
  - redo
  - htmlEmbed
