defaultPlacement: end
fieldLayouts:
  e83b2201-7752-407a-afd8-fe18f7d66fb5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: b0e214ac-5da7-4fb4-91cd-79362fb50c1a
            warning: null
            width: 100
        name: Content
        uid: 945b2c7b-96d4-497c-9fe5-4260e30103d8
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  5a949caa-356a-45ea-b408-2b267055c99c: # Padstone
    hasUrls: true
    template: null
    uriFormat: 'blog?category={slug}'
structure:
  maxLevels: 1
  uid: 7500937b-aa4b-4094-9a13-5480a3ca0589
