defaultPlacement: end
fieldLayouts:
  0200034e-9240-4485-a115-eeb0f4c05635:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-28T15:13:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 6dbd3155-2f22-4cdf-a319-8870b8374f03
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53b4adcb-2ea1-4727-a8ff-bb371c39be0a
        userCondition: null
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # Padstone Craft 5
    hasUrls: true
    template: blog-categories/_category.twig
    uriFormat: 'blog?category={slug}'
structure:
  maxLevels: 1
  uid: 915b01cb-f005-4d8d-a722-c6b560397669
