defaultPlacement: end
fieldLayouts:
  2ba11013-1268-4a0e-8609-24a02085b4ee:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 1d06fadc-f83f-4f4f-b599-cc4febf51cc5
            warning: null
            width: 100
        name: Content
        uid: 286d52e6-3b7c-4ddd-a130-befd745e2bba
handle: resourceTopics
name: 'Resource Topics'
siteSettings:
  5a949caa-356a-45ea-b408-2b267055c99c: # Padstone
    hasUrls: true
    template: null
    uriFormat: 'resources?topic={slug}'
structure:
  maxLevels: 1
  uid: 233ad37f-a943-4919-bc27-8a2115bb0b27
