handle: resourceTopics
name: 'Resource Topics'
siteSettings:
  5a949caa-356a-45ea-b408-2b267055c99c:
    hasUrls: true
    template: ''
    uriFormat: 'resources?topic={slug}'
structure:
  maxLevels: 1
  uid: 233ad37f-a943-4919-bc27-8a2115bb0b27
