defaultPlacement: end
fieldLayouts:
  94f73e32-a09b-431a-9ab1-a0d23ef7e870:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a0cd11c2-c4d3-4aa2-a6d6-25f1d013fc0e
            warning: null
            width: 100
        name: Content
        uid: a359910c-0963-4f11-be22-30665ae39f11
handle: resourceTypes
name: 'Resource Types'
siteSettings:
  5a949caa-356a-45ea-b408-2b267055c99c: # Padstone
    hasUrls: true
    template: null
    uriFormat: 'resources?type={slug}'
structure:
  maxLevels: 1
  uid: a05bccd3-a5b7-4519-a8de-a9fd24a1f6fe
