childBlocks: null
field: ccef03bc-c845-46cb-abd4-fa037632c2be # Content Designer (Basic)
handle: callToActionSection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Call to Action Section'
sortOrder: 10
topLevel: true
