childBlocks: null
field: ccef03bc-c845-46cb-abd4-fa037632c2be # Content Designer (Basic)
handle: iconGridSection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Icon Grid Section'
sortOrder: 14
topLevel: true
