childBlocks: null
description: null
field: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
fieldLayouts:
  5cdc95af-5b2d-4174-bd92-20a96589e54e:
    tabs:
      -
        elements:
          -
            fieldUid: 4cf8035e-3fdb-4fee-b44e-7876f8adc134 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12559511-bc95-46b7-beed-bb918afe5ad4
            warning: null
            width: 100
        name: Image
        uid: 825426db-93dc-48c5-b12e-04ff072ee756
group: null
handle: imageColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Image
sortOrder: 5
topLevel: false
