childBlocks: '*'
field: 76189277-255d-4e96-a6a5-6d393515b059 # Navigation Links
fieldLayouts:
  13e108f6-f294-410c-8ace-097ffc4c83d7:
    tabs:
      -
        elements:
          -
            fieldUid: 4e905e69-761d-4b9c-a8ab-9d27895e0bb5 # Link
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d7f939fa-2eec-4a25-a8ae-af842857ee2e # Column Span
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Navigation Link'
        sortOrder: 1
handle: navigationLink
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Navigation Link'
sortOrder: 1
topLevel: true
