childBlocks: ''
field: ccef03bc-c845-46cb-abd4-fa037632c2be # Content Designer (Basic)
handle: relatedEntryColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Related Entry'
sortOrder: 6
topLevel: false
