childBlocks:
  - relatedEntryColumn
description: null
field: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
fieldLayouts:
  4865a4c1-f239-43f7-a998-d463d7f51af4:
    tabs:
      -
        elements:
          -
            fieldUid: 63130e28-a0f4-4ccd-9398-6605090e3d4e # Section Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c925c42-eca4-4546-8daf-dbb6b9af0ea9
            warning: null
            width: 100
          -
            fieldUid: 7841a5cf-bd8c-4ea2-aa08-36e932a96da5 # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bebd2a4-f9da-46fa-a4ea-6fc69af48aef
            warning: null
            width: 100
          -
            fieldUid: 7ca1dc40-5807-4ca6-af3c-718be3e9615e # Section Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd948de6-5787-465c-a5f1-34a45687b68d
            warning: null
            width: 100
          -
            fieldUid: 4bdc4b1e-4dbc-47ad-8552-a6459c2c9644 # Section Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dd5e180-4c3c-4c9c-9b1c-81f95935d6dd
            warning: null
            width: 100
          -
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 6dd758d2-8db6-4088-bdef-d60198e53df7
          -
            fieldUid: 80c5c826-227b-4c52-a9c9-e314bb49a079 # Section Conclusion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d745d7fe-c9ac-48e4-87cb-caee62d8e976
            warning: null
            width: 100
          -
            fieldUid: acd8e61e-e2f0-4b23-900e-44658f2fa636 # Section Call to Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc921690-3359-475b-95c0-040bfa87d8b9
            warning: null
            width: 100
        name: 'Related Entries Section'
        uid: fc5998b9-79b1-4fa8-8c0d-85d4058723dd
      -
        elements:
          -
            fieldUid: d03466b4-3d0a-42cd-b219-2e36c817b6d2 # Section Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 331d17e0-cd85-4934-8ff5-d99b25960319
            warning: null
            width: 100
          -
            fieldUid: 861751dd-1c7f-4d7c-89df-f642306506be # Section Anchor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03b7a76c-ccfc-49d6-bd1f-fa839592dbaa
            warning: null
            width: 100
        name: Settings
        uid: 5032dc9c-aa45-4767-8212-15204aa4f22e
group: null
handle: relatedEntriesSection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Related Entries Section'
sortOrder: 11
topLevel: true
