childBlocks: ''
field: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
fieldLayouts:
  b6bd5fa4-c0bb-4903-a2bd-8bc0ad8e520d:
    tabs:
      -
        elements:
          -
            fieldUid: c50d8eef-596a-4828-932a-35ae42d726f7 # Related Entry
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4cf8035e-3fdb-4fee-b44e-7876f8adc134 # Image
            instructions: 'Provide an image for this entry. If not specified, will try to use the default image for this entry.'
            label: ''
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a85ee5b-d769-4583-9413-d29df8ebada2 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 39ab22fe-4e77-41e6-8c13-442f832d2fc4 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8484a0d1-2553-4939-bce7-c6a64087c06a # Call to Action Label
            instructions: 'Text to show on Call to Action.'
            label: 'Call to Action Label'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Related Entry'
        sortOrder: 1
handle: relatedEntryColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Related Entry'
sortOrder: 6
topLevel: false
