childBlocks: ''
field: ccef03bc-c845-46cb-abd4-fa037632c2be # Content Designer (Basic)
fieldLayouts:
  ec7fc98c-69aa-488c-9eed-a739f55bb27d:
    tabs:
      -
        elements:
          -
            fieldUid: 65565a16-00f4-46e1-8520-6975a775133d # Shared Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Shared Section'
        sortOrder: 1
handle: sharedSection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Shared Section'
sortOrder: 13
topLevel: true
