childBlocks: null
description: null
field: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
fieldLayouts:
  4b70d138-5028-4dc9-be21-ef934d519d3f:
    tabs:
      -
        elements:
          -
            fieldUid: 8e71eaa9-069f-4627-978b-04001165c7f5 # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1cfeba2-73a5-4bba-af34-78dce404e3db
            warning: null
            width: 100
          -
            fieldUid: 2f7d5293-4e8b-4788-92ac-68f0000f5b97 # Person
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c0f164b-33af-4f5f-9c76-18fcf95ca7c8
            warning: null
            width: 100
          -
            fieldUid: c6b109d5-1fc5-46a4-a61c-ffe6be120888 # Job Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 343f41e5-72b8-454b-b56c-20cc950ff55b
            warning: null
            width: 100
        name: Testimonial
        uid: cc04c1aa-56cb-4eb3-97bc-1b0fd24b77b8
group: null
handle: testimonialColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Testimonial
sortOrder: 7
topLevel: false
