childBlocks: null
field: ccef03bc-c845-46cb-abd4-fa037632c2be # Content Designer (Basic)
handle: testimonialSection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Testimonial Section'
sortOrder: 12
topLevel: true
