childBlocks:
  - callToActionColumn
field: ccef03bc-c845-46cb-abd4-fa037632c2be # Content Designer (Basic)
handle: textColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Text
sortOrder: 3
topLevel: false
