childBlocks: ''
field: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
fieldLayouts:
  66bc46fc-a268-4fc8-8e5e-e31bb04cb456:
    tabs:
      -
        elements:
          -
            fieldUid: bf421a3c-f1ec-450f-9a71-564c29401db5 # Video
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Video
        sortOrder: 1
handle: video
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Video
sortOrder: 8
topLevel: false
