childBlocks: null
field: 2b415ab0-c680-4dd1-acfd-0d1edb5452a8 # Content Designer
fieldLayouts:
  f6787b4f-a925-40a7-8319-f745c048366c:
    tabs:
      -
        elements:
          -
            fieldUid: 4cf8035e-3fdb-4fee-b44e-7876f8adc134 # Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Image
        sortOrder: 1
handle: weightedImageColumn
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Weighted Image'
sortOrder: 6
topLevel: false
