altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0ba7637d-8f14-4ad6-ab57-371c7fe7c365:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T18:15:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f57fddfc-ba21-4207-9ce0-ed7b603f9bea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T18:16:53+00:00'
            elementCondition: null
            fieldUid: e49eee72-0b33-43a2-81d6-31fb4ab32346 # Alt Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b451b94-2bee-47cb-86fe-5a4a628f1732
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f5d8edde-1306-4cf3-934e-0a5d50adf7d2
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
