altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4586306d-79d1-4846-9307-b289cf6ec402:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T18:16:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9f67fb6a-048b-4d41-a001-9f8f237cfa10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2ca820f-393f-47f6-bd0c-6e2f4402fa0b
        userCondition: null
fs: resources
handle: resources
name: Resources
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
