fieldLayouts:
  f63138a4-8e35-4089-9e95-bf35d7b37f91:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bf16ec65-d998-4fc2-a91d-4e59d8946b16
            warning: null
            width: 100
        name: Content
        uid: cc86b6e8-4cca-4b3a-9d13-8f19d9eb1efd
fs: resources
handle: resources
name: Resources
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
