columnSuffix: null
contentColumnType: text
fieldGroup: c4593c73-7ed0-4694-9aa8-fa73bd8c1b1b # Common
handle: abstract
instructions: 'Short description for lists.'
name: Abstract
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
