columnSuffix: null
handle: abstract
instructions: null
name: Abstract
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: d69400d5-37c7-48ef-b143-e25cccdda2ac # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
