columnSuffix: null
contentColumnType: text
fieldGroup: c4593c73-7ed0-4694-9aa8-fa73bd8c1b1b # Common
handle: abstract
instructions: 'Short description for lists.'
name: Abstract
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Standard.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
