columnSuffix: null
handle: blockContent
instructions: null
name: Content
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: c164bcf4-0226-4e9f-bfe0-ca08ad8056b5 # Full
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  entryTypes:
    - 976d4ccf-4988-4c36-968c-53f396dce7f2 # Blog Article
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
