columnSuffix: null
handle: ctaLink
instructions: 'Leave blank to create a heading with no link'
name: Link
searchable: false
settings:
  maxLength: 255
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
  types:
    - url
    - asset
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
