columnSuffix: null
handle: footerNavItems
instructions: null
name: 'Footer Navigation Items'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:0e0a0c15-2d54-4a63-b4ae-29b75916437e' # Navigation
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
