columnSuffix: null
contentColumnType: text
fieldGroup: 8f7d8f4f-3a1e-4cc7-bae6-46b4406f2188 # Globals
handle: navigationHeading
instructions: 'Group links under a heading that isn''t a link itself.'
name: 'Navigation Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
