columnSuffix: null
handle: navigationGroups
instructions: null
name: 'Navigation Groups'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - fa15f698-a1ed-4140-9c8d-02eac44b66b4 # Navigation Group
    - 8b3d1977-ab5a-4ca6-94cb-685acdef3921 # Navigation Link
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
