columnSuffix: null
contentColumnType: text
fieldGroup: 28bbb761-2bca-4754-ba9e-c0bfe22f4496 # People
handle: personJobTitle
instructions: null
name: 'Job Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
