contentColumnType: string
fieldGroup: 8f7d8f4f-3a1e-4cc7-bae6-46b4406f2188
handle: primaryNavItems
instructions: ''
name: 'Primary Nav Items'
searchable: true
settings:
  contentTable: '{{%matrixcontent_primarynavitems}}'
  maxBlocks: '6'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
