columnSuffix: null
handle: resourceTopics
instructions: null
name: 'Resource Topics'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a Topic'
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:de18a008-1675-459b-bc1e-5f684096b0c2' # Resource Topics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
