columnSuffix: null
contentColumnType: text
fieldGroup: bbb87adb-e632-4579-b223-79796ba4ff1a # Resources
handle: resourceEmbed
instructions: 'Paste code to embed a video or other widget here.'
name: Embed
searchable: true
settings:
  mode: ''
translationKeyFormat: null
translationMethod: none
type: luwes\codemirror\fields\CodeMirrorField
