columnSuffix: null
contentColumnType: text
fieldGroup: 568aabd9-1216-4eea-9964-b4797c17d02f # Neo
handle: sectionCTALabel
instructions: null
name: 'Call to Action Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
