columnSuffix: null
contentColumnType: string
fieldGroup: 568aabd9-1216-4eea-9964-b4797c17d02f # Neo
handle: sectionBackground
instructions: null
name: 'Section Background'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - template
          - ''
        -
          - background
          - ''
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - White
        -
          - template
          - '<div style="background: white; width: 100%; aspect-ratio: 2; "></div>'
        -
          - background
          - white
        -
          - value
          - '-white'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - template
          - '<div style="background: #191c26; width: 100%; aspect-ratio: 2; "></div>'
        -
          - background
          - '#a2aac3'
        -
          - value
          - '-dark'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: Imarc\Pickture\fields\PicktureField
