columnSuffix: null
contentColumnType: text
fieldGroup: 568aabd9-1216-4eea-9964-b4797c17d02f # Neo
handle: sectionConclusion
instructions: 'Similar to the introduction, but shown at the end of the section.'
name: 'Section Conclusion'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: 'Simple (Allow Links).json'
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
