contentColumnType: string
fieldGroup: 568aabd9-1216-4eea-9964-b4797c17d02f # Neo
handle: sectionAnchor
instructions: "Adds an anchor to the header so that a link can be added elsewhere on the page to jump to this section. The anchor must be URL friendly so you may only use alphanumeric characters, dashes and underscores. Reminder that the anchor must be UNIQUE per page, otherwise there will be conflicts. E.g. page-section\r\n\r\nIn the URL field to link to this section, you will enter the URL to the page (can be just the path without the domain) with '#' plus the string you provide. Example: '/page-url#page-section'."
name: 'Section Anchor'
searchable: false
settings:
  customPattern: '^[a-zA-Z0-9_-]*$'
  customPatternErrorMessage: 'You may only use alphanumeric characters, dashes and underscores.'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: barrelstrength\sproutfields\fields\RegularExpression
