dateModified: 1645036480
email:
  fromEmail: kevin@imarc.com
  fromName: Padstone
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0bcdc18c-156d-4d49-b4fe-272e7d33ff45: Alert # Alert
    0f8aa3f7-de9e-4beb-a7e9-e98793b3b60e: 'Featured Image' # Featured Image
    1cd65752-f86f-48a3-9924-90919c9ca915: Homepage # Homepage
    1ea4259c-e128-4613-8411-7fdff7c0b9a4: 'Standard Hero' # Standard Hero
    1eb9445b-5596-41c4-b25c-ec44e9a4ec0a: 'Team Member' # Team Member
    1f72f453-c1cd-4abf-9dda-f57179b39bd5: Content # Content
    1fe0cd4d-bad9-4dc9-93c8-5c42c53b930c: Eyebrow # Eyebrow
    2b415ab0-c680-4dd1-acfd-0d1edb5452a8: 'Content Designer' # Content Designer
    2bce713c-e1dd-4517-8bf0-60f2c1165bc3: 'Blog Article' # Blog Article
    2ddfd638-9959-4fb7-877b-10b6424503bc: 'Service Unavailable Page' # Service Unavailable Page
    2e868be5-415e-4f7c-b96c-160e9091705c: 'Call to Action' # Call to Action
    2f7d5293-4e8b-4788-92ac-68f0000f5b97: Person # Person
    4bdc4b1e-4dbc-47ad-8552-a6459c2c9644: 'Section Introduction' # Section Introduction
    4c423460-9459-4217-bb67-abe4dbd0e889: 'Related Entry' # Related Entry
    4cd84b5c-0162-4148-a588-37b2fcc1da0a: SEO # SEO
    4cf8035e-3fdb-4fee-b44e-7876f8adc134: Image # Image
    4e905e69-761d-4b9c-a8ab-9d27895e0bb5: Link # Link
    4f214271-7640-4763-948d-3eb791a16473: Location # Location
    5a97a103-aef5-4566-8db5-0f54befee146: 'Call to Action' # Call to Action
    5a949caa-356a-45ea-b408-2b267055c99c: Padstone # Padstone
    5ca24464-6fc5-4ec1-b72f-bd44b3d7f72f: 'Shared Section' # Shared Section
    6a85ee5b-d769-4583-9413-d29df8ebada2: Label # Label
    6c97b95b-c74a-41d8-be93-7607a191617d: 'Resource Topics' # Resource Topics
    7b352338-e4c1-4527-8c7b-dd3ae5e9d28f: Events # Events
    7ca1dc40-5807-4ca6-af3c-718be3e9615e: 'Section Subheading' # Section Subheading
    7d9b0c79-765b-45bd-b16c-8111fa98160c: Image # Image
    7fb04d4d-68f6-468b-806c-a3184fe19671: 'Contact Page' # Contact Page
    8c2e7523-1da7-4283-8f22-be2cfd5d251b: 'Select Hero' # Select Hero
    8db154b4-31aa-4a46-bd7e-e040f96b91a8: 'Call to Action' # Call to Action
    8e71eaa9-069f-4627-978b-04001165c7f5: Quote # Quote
    8f7d8f4f-3a1e-4cc7-bae6-46b4406f2188: Globals # Globals
    8fda9d17-0a07-4bc1-a1f4-1fe23066f315: 'Alt Text' # Alt Text
    9b2e55cd-41cc-43c8-a0e9-17aa24519787: Pages # Pages
    9de11a83-392f-4ebb-9d01-e5ebaf22cf18: 'Resource with Detail Page' # Resource with Detail Page
    9e20857f-1af8-4551-a171-4756ce866036: 'SEOMatic Fields' # SEOMatic Fields
    9f476afb-8d57-45ac-9e4e-ce0e167717f3: Testimonial # Testimonial
    15b2f480-fc8a-4c46-b7a9-0aaf337686ed: Classes # Classes
    16e6b8c8-fd2d-4fa3-9219-9d81e2ab1e98: 'Shared Sections' # Shared Sections
    26f42a7b-fe45-4cc5-9535-49a9e14a7446: Date # Date
    28bbb761-2bca-4754-ba9e-c0bfe22f4496: People # People
    33b1f8a4-938d-4514-bd23-d7b4e457fb8f: Video # Video
    48df7913-438b-433b-96d3-163d33a83ea7: Photo # Photo
    49c29c1d-a40b-4fdc-b79e-237911ae899b: 'Footer Navigation' # Footer Navigation
    78c81b0b-cb55-4a9e-b5c9-4d4316b19255: Headline # Headline
    80c5c826-227b-4c52-a9c9-e314bb49a079: 'Section Conclusion' # Section Conclusion
    82a2c8bb-e9ac-4ea3-b6a7-9ed9a46b019c: Subheadline # Subheadline
    87fa42ae-cdb3-48ca-a5b4-80df97ced5bc: 'Icon Grid' # Icon Grid
    93c50f97-bc7e-49e9-8963-7ef0419aed10: 'Resources Page' # Resources Page
    93e2b1ce-6b60-40c8-ad40-4b1c92d2ecd1: Resource # Resource
    349bc9d5-448b-4314-a81e-d76e7cca8758: 'News Article' # News Article
    380fab36-d288-4b53-9d1b-d5aad2afc914: 'Blog Categories' # Blog Categories
    489b2a3b-26f2-4b85-a9fc-bf800e523764: Text # Text
    550e9481-b606-4b2b-83e1-9a895a224d38: 'News Articles' # News Articles
    568aabd9-1216-4eea-9964-b4797c17d02f: Neo # Neo
    0610a849-e9bc-455c-86d5-ee8175b2ae9a: Embed # Embed
    804ebac0-45d8-49c0-9e1f-418cc9c708e7: Homepage # Homepage
    2575b2df-9c7d-43dc-b00c-7c8b4a389b22: Abstract # Abstract
    6978af6e-566d-496d-abfc-884513d509b9: Alert # Alert
    7841a5cf-bd8c-4ea2-aa08-36e932a96da5: 'Section Heading' # Section Heading
    08386a69-e42e-4991-b576-378c5250a491: 'Team Page' # Team Page
    8484a0d1-2553-4939-bce7-c6a64087c06a: 'Call to Action Label' # Call to Action Label
    09773b73-a304-4513-84fd-c4d5d4dd953a: Images # Images
    057820ca-40a4-4854-9da1-7e9d88fc255f: 'Call to Action' # Call to Action
    63130e28-a0f4-4ccd-9398-6605090e3d4e: 'Section Eyebrow' # Section Eyebrow
    65565a16-00f4-46e1-8520-6975a775133d: 'Shared Section' # Shared Section
    86444c22-bd97-4a40-9136-f5613c95ba48: 'Resource Types' # Resource Types
    437719cf-795d-42cf-8b92-2ea1224939b4: 'Direct Link' # Direct Link
    754177a1-494c-4f11-806a-112af873ab1d: '404 Page' # 404 Page
    861751dd-1c7f-4d7c-89df-f642306506be: 'Section Anchor' # Section Anchor
    969995e1-dbd5-42c5-917f-a13e492a5c83: Homepage # Homepage
    5069846c-87c5-4a46-948a-490c04176e01: 'Related Entries Section' # Related Entries Section
    6533045f-a95c-45a5-a67a-c8da4cec0d5d: News # News
    13855676-b0ca-477b-b838-6bfaa2d2c4da: Alerts # Alerts
    31726602-42e3-461e-ad79-08d69e6e899a: Resources # Resources
    50143545-7495-4722-9929-a0651b8110dd: 'Navigation Heading' # Navigation Heading
    54928315-c91e-43dd-9a25-ef7bb9d4a906: 'Designed Section' # Designed Section
    57423459-e14e-4a06-af08-3f1c378379ba: Resources # Resources
    61009477-6ca8-4122-b871-b3b715eec012: Events # Events
    76189277-255d-4e96-a6a5-6d393515b059: 'Navigation Links' # Navigation Links
    a3f637cc-edb1-4bae-83f3-a40127804401: Bio # Bio
    a20a79e6-31e4-4179-833c-e756db8c0d15: Padstone # Padstone
    a84f71b8-e8a5-4c29-8a33-234af848c374: 'Call to Action Section' # Call to Action Section
    a889cfc2-e16d-4719-88be-773bf11567f4: 'Blog Categories' # Blog Categories
    a3601ba7-e21f-4718-86f2-0c19eae0d32f: 'Job Title' # Job Title
    a49945ef-0bec-4fcd-98f8-0e8eb19bbc0a: 'Embed or Code' # Embed or Code
    aa4b309e-df7a-47cf-9aa5-25285f46796f: '404 Page' # 404 Page
    acd8e61e-e2f0-4b23-900e-44658f2fa636: 'Section Call to Action' # Section Call to Action
    ae6274b5-2c31-48b8-b5db-a76a57f152d5: 'Background Image' # Background Image
    b2e9d0fb-ba4b-4b23-9fcf-459ad68c0ea9: Blog # Blog
    b6cd1ab1-15c9-44a7-a272-96583dc2757b: Icon # Icon
    b7a6ad8e-d32a-4f3b-9ac7-c8a0d7d9e616: Alerts # Alerts
    b24b0539-2cd5-45dd-b919-cab05bad8f6c: Embed # Embed
    b51bd305-59f1-4781-ab0f-0a42ffb8d856: 'Navigation Link' # Navigation Link
    b54bac54-a6a2-4e19-af8b-eead56deed68: Author # Author
    b233c231-ff4b-4157-8c2e-6cc6affca07e: Page # Page
    bbb87adb-e632-4579-b223-79796ba4ff1a: Resources # Resources
    bc736b97-4ff9-4fc1-a2c6-29b4a07fdba6: 'Rich Text Section' # Rich Text Section
    bca12576-fed9-4ec6-8597-2011bc9e21da: 'Primary Navigation' # Primary Navigation
    be750023-509f-45ce-b784-9d099cd2fe28: 'Content (No Media)' # Content (No Media)
    bf421a3c-f1ec-450f-9a71-564c29401db5: Video # Video
    c2b63486-bb0e-42d6-9986-12cead0acc47: 'Blog Date' # Blog Date
    c2f6ae57-a58a-4ddb-8776-b3510df685a6: 'Start Date' # Start Date
    c2fc9bf0-5ff5-4af8-ae54-5ca0a7ce5db4: Abstract # Abstract
    c6b109d5-1fc5-46a4-a61c-ffe6be120888: 'Job Title' # Job Title
    c50d8eef-596a-4828-932a-35ae42d726f7: 'Related Entry' # Related Entry
    c87b5acc-afe1-4ddf-b73c-b449c9f29c2d: Team # Team
    c3550c6e-2988-47b1-abaa-269c8443d75f: 'News Page' # News Page
    c4593c73-7ed0-4694-9aa8-fa73bd8c1b1b: Common # Common
    ca915fd0-926d-4128-b286-ce7f553add12: 'Resource Topics' # Resource Topics
    caff8cda-08a9-48d3-99dc-c859723eca26: 'Icon Grid Section' # Icon Grid Section
    cbbf18dd-b228-4f6e-bebb-dd1f1682da10: 'Navigation Group' # Navigation Group
    cd059144-5cb6-46db-bcea-8d8e1d747107: 'End Date' # End Date
    d03466b4-3d0a-42cd-b219-2e36c817b6d2: 'Section Background' # Section Background
    d1edff97-994f-4f78-9318-6cdbbdfd446d: 'Additional Header Code' # Additional Header Code
    d4b08b90-6f7d-4229-84e7-aca47f73edba: 'Testimonial Section' # Testimonial Section
    d5e98a9a-c478-4cf5-8c85-1083950e2e9f: 'Resource Date' # Resource Date
    d7f939fa-2eec-4a25-a8ae-af842857ee2e: 'Column Span' # Column Span
    d9b26dd3-8815-474a-b2d1-df10d1da9ea4: 'Resource Types' # Resource Types
    d44a5a95-fa08-4efd-8496-2ac825c5acd1: 'Service Unavailable Page' # Service Unavailable Page
    d2034a01-128e-4603-bb49-a8367850dc96: Introduction # Introduction
    e3c0ba5c-47fe-4162-b36a-d145f282a972: 'Shared Section' # Shared Section
    e60a84f5-789c-489b-a95e-ae0419f4ae7d: 'Additional Footer Code' # Additional Footer Code
    e43112ef-9196-4187-9567-345e3181f3b2: 'Weighted Image' # Weighted Image
    e715570c-a506-4c8b-b940-48378d3a8448: Icon # Icon
    e6810524-42e4-4e35-8fe8-edfb548dd138: Description # Description
    eaed0b39-140d-4da6-8c44-9e192f8a76be: 'Blog Page' # Blog Page
    eea7d11e-037c-44d7-a992-bd1eaf2b3f72: Authors # Authors
    f1e078e0-561e-47be-a5bb-1ad7b61ab109: Event # Event
    f7ade5a5-61b5-4252-b776-39dd9f92d0fc: Authors # Authors
    f68e9a51-f020-4eaf-8378-33e8197236a8: Label # Label
    f243ce8b-892c-4b86-9d26-18e95335b564: 'Public Schema' # Public Schema
    fcc7f6c3-97c3-4ab3-8555-f630f7deb9cb: Abstract # Abstract
    fdc8d709-53c4-4104-ba7b-f424bad5b7fc: 'Blog Articles' # Blog Articles
    fe9f15e5-2b68-477e-af16-c6e83c83e642: 'Featured Image' # Featured Image
plugins:
  admin-bar:
    enabled: '1'
    licenseKey: null
    schemaVersion: 3.1.0
    settings:
      bgColor: '#000000'
      cacheBar: true
      customLinks:
        -
          adminOnly: ''
          linkLabel: foo
          linkUrl: fooo
      displayDashboardLink: true
      displayDefaultEditSection: true
      displayEditAuthor: true
      displayEditDate: true
      displayGreeting: true
      displayLogout: true
      displayRevisionNote: true
      displaySettingsLink: true
      enableMobileMenu: true
      highlightColor: '#D85B4B'
      scrollLinks: true
      textColor: '#FFFFFF'
  code-mirror:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  contact-form:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  contact-form-honeypot:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  craft-kindling:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  googlecustomsearch:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  mix:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      assetPath: /
      publicPath: web
  neo:
    edition: standard
    enabled: true
    licenseKey: EJDC0EFFBVJWC4IDGXKLNLLX
    schemaVersion: 2.11.6
  pickture:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
  retour:
    edition: standard
    enabled: true
    licenseKey: ZBZ3UQOSANUAPT9YZRRUZAHZ
    schemaVersion: 3.0.10
  seomatic:
    edition: standard
    enabled: true
    licenseKey: IL7KLC0Y2B2BX6DTIO9QTGIM
    schemaVersion: 3.0.11
  sprout-fields:
    edition: standard
    enabled: true
    schemaVersion: 3.5.3
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
system:
  edition: solo
  live: true
  name: Padstone
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
