field: 973e24a8-d7d9-4072-83fc-5e86d98ba38c
fieldLayouts:
  068a98b9-5280-4125-86a9-ccd726964bce:
    tabs:
      -
        fields:
          a5122e92-6ea2-485f-90de-d19fa34b7964:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  a5122e92-6ea2-485f-90de-d19fa34b7964:
    contentColumnType: text
    fieldGroup: null
    handle: blockLink
    instructions: "You may select an entry, provide a URL or link to an asset for column links.\r\n\r\nPlease note: if you choose to provide a URL, you MUST also provide \"Custom link text\", otherwise the link will appear blank. Entry links with no custom link text will fall back on the title of the entry. Asset links with no custom link text will use the name of the file."
    name: Link
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames:
        1: asset
        3: entry
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
