fieldLayouts:
  f69485a5-76cd-4bc9-aa1c-64e4c3d68b22:
    tabs:
      -
        fields:
          845c4d3c-77ca-498c-abfc-c923b56c257a:
            required: true
            sortOrder: 1
        name: 'Footer Navigation'
        sortOrder: 1
handle: footerNavigation
name: 'Footer Navigation'
