fieldLayouts:
  f69485a5-76cd-4bc9-aa1c-64e4c3d68b22:
    tabs:
      -
        elements:
          -
            fieldUid: 76189277-255d-4e96-a6a5-6d393515b059 # Navigation Links
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a7d3c00-6947-4e03-a988-2dec004808f7
            warning: null
            width: 100
        name: 'Footer Navigation'
        uid: cb248edc-18a9-4a2d-b5cb-ce603b8f1593
handle: footerNavigation
name: 'Footer Navigation'
sortOrder: 2
