fieldLayouts:
  014ddd99-77a7-4955-91d9-ce04f130e3a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-16T15:22:11+00:00'
            elementCondition: null
            fieldUid: 6eef63ba-f2a8-4833-8b72-8a6a9d931f84 # Navigation Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9feab9f3-c071-43a1-a027-21a6c9f8672a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25a2aebb-4c5f-456e-b22c-beeb4aab3a9f
        userCondition: null
handle: primaryNavigation
name: 'Primary Navigation'
sortOrder: 1
