fieldLayouts:
  9ac4610a-b9fc-4b41-b3e9-223b0280e8d0:
    tabs:
      -
        fields:
          5a295f2c-c2ce-40c0-b50c-23f6c88f66a5:
            required: false
            sortOrder: 3
          09eace92-99e5-4c80-b462-0bc90dc92379:
            required: false
            sortOrder: 2
          849e9f92-3a0a-42d1-a8a5-8d4e53e8cbdf:
            required: false
            sortOrder: 4
          d0ef6070-9d0c-4998-b117-5233a7251716:
            required: false
            sortOrder: 1
        name: 'Social Links'
        sortOrder: 1
handle: socialLinks
name: 'Social Links'
