enableVersioning: true
handle: alerts
name: Alerts
propagationMethod: all
siteSettings:
  5a949caa-356a-45ea-b408-2b267055c99c: # Padstone
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 2151ab86-6794-41cc-974a-c1af5b7d2213
type: structure
