defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 976d4ccf-4988-4c36-968c-53f396dce7f2 # Blog Article
handle: blogArticle
maxAuthors: 1
minAuthors: 1
name: 'Blog Articles'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # $CRAFT_SITENAME
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
