defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0526dbf2-583a-4dc9-83f5-f5888101378b # Event
handle: events
maxAuthors: 1
minAuthors: 1
name: Events
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # $CRAFT_SITENAME
    enabledByDefault: true
    hasUrls: true
    template: events/_entry.twig
    uriFormat: 'events/{slug}'
type: channel
