defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c46e2b3b-387a-4540-9120-ab0a15b0bbae # Homepage
handle: homepage
maxAuthors: 1
minAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # Padstone
    enabledByDefault: true
    hasUrls: true
    template: _index
    uriFormat: __home__
type: single
