defaultPlacement: end
enableVersioning: true
entryTypes:
  - ae7af0c4-5df7-45d3-aa71-3888882dd594 # News Article
  - 8a9cd262-8604-45fd-a48d-b11f4d398ba7 # Press Mention
handle: news
maxAuthors: 1
name: 'News Articles'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # Padstone Craft 5
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
