enableVersioning: true
handle: notFoundPage
name: '404 Page'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5a949caa-356a-45ea-b408-2b267055c99c:
    enabledByDefault: true
    hasUrls: true
    template: _404
    uriFormat: '404'
type: single
