defaultPlacement: end
enableVersioning: true
entryTypes:
  - c2f04b66-544d-449f-a4de-c5605f121afd # Team Member
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # Padstone Craft 5
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
