defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c2f04b66-544d-449f-a4de-c5605f121afd # Team Member
handle: team
maxAuthors: 1
minAuthors: 1
name: Team
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # $CRAFT_SITENAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
